name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Build
      run: |
        npm install
        npx webpack
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: public-folder
        path: public
